import os
import json
from typing import TypedDict, List, Dict, Any, Union
from langgraph.graph import StateGraph, END
from litellm import completion
from .sandbox import Sandbox

# State definition
class AgentState(TypedDict):
    task_description: str
    developer_output: Dict[str, Any]
    validator_output: Dict[str, Any]
    retry_count: int
    max_retries: int
    history: List[Dict[str, Any]]

class Orchestrator:
    def __init__(self, model="ollama/llama3", sandbox_config="validator_config.yaml"):
        self.model = model
        self.sandbox = Sandbox(sandbox_config)
        
        # Load prompts
        with open("prompts/developer.md", "r") as f:
            self.developer_prompt = f.read()
        with open("prompts/validator.md", "r") as f:
            self.validator_prompt = f.read()

        # Build Graph
        workflow = StateGraph(AgentState)
        
        workflow.add_node("developer", self.developer_node)
        workflow.add_node("validator", self.validator_node)
        
        workflow.set_entry_point("developer")
        
        workflow.add_conditional_edges(
            "validator",
            self.should_continue,
            {
                "continue": "developer",
                "end": END
            }
        )
        workflow.add_edge("developer", "validator")
        
        self.app = workflow.compile()

    def developer_node(self, state: AgentState):
        print(f"--- DEVELOPER NODE (Attempt {state['retry_count'] + 1}) ---")
        
        messages = [
            {"role": "system", "content": self.developer_prompt},
            {"role": "user", "content": f"Task: {state['task_description']}"}
        ]
        
        # Add feedback if it's a retry
        if state['retry_count'] > 0:
            last_fail = state['validator_output']
            messages.append({"role": "assistant", "content": json.dumps(state['developer_output'])})
            messages.append({"role": "user", "content": f"Test failures detected:\n{last_fail['error_trace']}\nPlease fix the code."})

        response = completion(model=self.model, messages=messages)
        content = response.choices[0].message.content
        
        # Clean potential markdown bubbles
        if "```json" in content:
            content = content.split("```json")[1].split("```")[0].strip()
        elif "```" in content:
            content = content.split("```")[1].split("```")[0].strip()
            
        try:
            dev_json = json.loads(content)
        except json.JSONDecodeError:
            # Fallback for malformed JSON
            dev_json = {"files": [], "error": "Malformed JSON output"}

        return {"developer_output": dev_json}

    def validator_node(self, state: AgentState):
        print("--- VALIDATOR NODE ---")
        dev_output = state['developer_output']
        
        if not dev_output.get("files"):
            return {
                "validator_output": {
                    "status": "FAIL", 
                    "error_trace": "No files generated by Developer.",
                    "retry_count": state['retry_count']
                }
            }

        status, logs = self.sandbox.run_tests(dev_output["files"])
        
        validator_json = {
            "status": status,
            "error_trace": logs,
            "retry_count": state['retry_count']
        }
        
        return {
            "validator_output": validator_json,
            "retry_count": state['retry_count'] + 1
        }

    def should_continue(self, state: AgentState):
        v_output = state['validator_output']
        if v_output["status"] == "PASS":
            print("--- SUCCESS: All tests passed! ---")
            return "end"
        
        if state['retry_count'] >= state['max_retries']:
            print("--- FAILURE: Max retries reached. ---")
            return "end"
        
        print(f"--- RETRYING: Tests failed. {state['max_retries'] - state['retry_count']} retries left. ---")
        return "continue"

    def run(self, task_description: str, max_retries=3):
        initial_state = {
            "task_description": task_description,
            "developer_output": {},
            "validator_output": {},
            "retry_count": 0,
            "max_retries": max_retries,
            "history": []
        }
        return self.app.invoke(initial_state)
